# Generated by Django 2.2.7 on 2019-11-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_topping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
    ]
