# Generated by Django 2.2.7 on 2019-12-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_my_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_order',
            old_name='userid',
            new_name='user',
        ),
    ]
