# Generated by Django 2.2.7 on 2019-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191201_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
