# Generated by Django 2.2.7 on 2019-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_topping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='groupname',
            field=models.CharField(default='pizza', max_length=64),
        ),
    ]
