# Generated by Django 2.2.7 on 2019-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_my_order_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='size',
            field=models.CharField(default='mediam', max_length=64),
        ),
    ]
